# Generated by Django 5.2 on 2025-04-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20250413_1608'),
    ]

    operations = [
    ]
