# Generated by Django 5.2 on 2025-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_id_alter_book_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='generate_book_id', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
