# Generated by Django 5.2 on 2025-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_book_id_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
