# Generated by Django 5.2 on 2025-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='requester_profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
